### ISSUE TITLE
sudo not necessary for building a Docker container (?)

### ISSUE THREAD

**Issue by kinow** [GenomicsAotearoa/EWAS_DAP#6]
In the readme, it points the user to use `sudo` for building a Docker container. But if users have right group access in the operating system, there's no need for `sudo`. Only when using the privileged mode for running I think.

I've successfully built it without the `sudo` (though it took ages, which is normal :grimacing: I believe).

**Comment by markolaban** [comment]
Thanks for raising this, I have updated documentation so perhaps you could give it a read and let me know if it makes more sense?
We were developing this on HPC that currently doesn't have Docker available and all the VMs are set up with CentOS so in our case sudo was the only available option.
It's worthwhile reading this (a bit dated) info on the potential risks: https://www.projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/

**Comment by kinow** [comment]
It looks good to me @markolaban , thanks for fixing it so quickly.

The part about being able to build without sudo, and also the part about rootless, both look good to me :+1: will close this issue.

Cheers
Bruno
